In [1]:
import numpy as np

In [8]:
image4 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])-1
dim=5
image5 = np.arange(dim**2).reshape(dim,dim)
print(image4)
print(image5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [136]:
h=5
w=5
im = np.arange(h*w).reshape(h,w)
print(im)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [137]:
fh = 3
fw = 3

In [138]:
zh = ((fh+1)//2)-1
zw = ((fw+1)//2)-1
print(zh, zw)

1 1


In [168]:
y=h-(2*zh)
x=w-(2*zw)
print(y,x)

3 3


In [169]:
num_p = (x*y)
print(num_p)

9


In [170]:
p = ((i+zh)*(w)) + zw + (j)
print(p)

18


In [171]:
ps = []
for i in range(y):
    for j in range(x):
        print(i,j)
        p = ((i+zh)*(w)) + zw + (j)
        # print(p)
        ps.append(p)
print(len(ps),ps)

0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2
9 [6, 7, 8, 11, 12, 13, 16, 17, 18]


In [144]:
yy,xx=np.meshgrid(np.arange(y),np.arange(x))
print(yy,xx)
# XY=np.array([yy.flatten(order='F'),xx.flatten(order='F')]).T
# print(XY)

[[0 1 2]
 [0 1 2]
 [0 1 2]] [[0 0 0]
 [1 1 1]
 [2 2 2]]


In [161]:
p = ((yy+zh)*(w)) + zw + (xx)
p = p.T.flatten().reshape(-1,1)
print(p)

[[ 6]
 [ 7]
 [ 8]
 [11]
 [12]
 [13]
 [16]
 [17]
 [18]]


In [157]:
n = np.zeros((len(p),8))
for e, pp in enumerate(p):
    n[e,0] = pp-h-1
    n[e,1] = pp-h
    n[e,2] = pp-h+1
    n[e,3] = pp-1
    n[e,4] = pp+1
    n[e,5] = pp+h-1
    n[e,6] = pp+h
    n[e,7] = pp+h+1
print(n)

[[ 0.  1.  2.  5.  7. 10. 11. 12.]
 [ 1.  2.  3.  6.  8. 11. 12. 13.]
 [ 2.  3.  4.  7.  9. 12. 13. 14.]
 [ 5.  6.  7. 10. 12. 15. 16. 17.]
 [ 6.  7.  8. 11. 13. 16. 17. 18.]
 [ 7.  8.  9. 12. 14. 17. 18. 19.]
 [10. 11. 12. 15. 17. 20. 21. 22.]
 [11. 12. 13. 16. 18. 21. 22. 23.]
 [12. 13. 14. 17. 19. 22. 23. 24.]]


In [163]:
print(im.T)

[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]


In [162]:
hh = np.array([[-h-1,-h,-h+1,-1,+1,h-1,h,h+1]])
n = p+hh
print(n)

[[ 0  1  2  5  7 10 11 12]
 [ 1  2  3  6  8 11 12 13]
 [ 2  3  4  7  9 12 13 14]
 [ 5  6  7 10 12 15 16 17]
 [ 6  7  8 11 13 16 17 18]
 [ 7  8  9 12 14 17 18 19]
 [10 11 12 15 17 20 21 22]
 [11 12 13 16 18 21 22 23]
 [12 13 14 17 19 22 23 24]]


In [82]:
ps = []
for i in range(y):
    for j in range(x):
        n = np.zeros(8)
        p = ((i+zh)*(w)) + zw + (j)
        n[0] = j
        n[1] = j+1
        n[2] = j+2
        n[3] = (i*y) + j
        n[4] = (i*y) + j + 2
        n[5] = (i*y) + j
        n[6] = (i*y) + j+1
        n[7] = (i*y) + j+2
        print(n)
        # ps.append(p)
print(len(ps),ps)

[0. 1. 2. 0. 2. 0. 1. 2.]
[1. 2. 3. 1. 3. 1. 2. 3.]
[0. 1. 2. 2. 4. 2. 3. 4.]
[1. 2. 3. 3. 5. 3. 4. 5.]
0 []


In [167]:
im.T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [166]:
print(im.T.flatten()[n])

[[ 0  5 10  1 11  2  7 12]
 [ 5 10 15  6 16  7 12 17]
 [10 15 20 11 21 12 17 22]
 [ 1  6 11  2 12  3  8 13]
 [ 6 11 16  7 17  8 13 18]
 [11 16 21 12 22 13 18 23]
 [ 2  7 12  3 13  4  9 14]
 [ 7 12 17  8 18  9 14 19]
 [12 17 22 13 23 14 19 24]]
